name: Build release binary

on:
  push:
    tags:
    - '*'

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      env:
        PYINSTALLER_COMPILE_BOOTLOADER: 1
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pyinstaller --no-binary pyinstaller
    - name: Build binary
      run: pyinstaller -i iMorphUpdater.ico --onefile -y --console --name iMorphUpdater --noupx runner.py
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: dist/iMorphUpdater.exe

  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build binary
      run: pyinstaller -i iMorphUpdater.ico --onefile -y --console --name iMorphUpdater --noupx runner.py
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: dist/iMorphUpdater
